version: '3.1'

services:

  mongo:
    image: mongo:5.0.3
    container_name: go-ecommerce-mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: development
      MONGO_INITDB_ROOT_PASSWORD: testpassword
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - default

  mongo-express:
    image: mongo-express
    container_name: go-ecommerce-mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: development
      ME_CONFIG_MONGODB_ADMINPASSWORD: testpassword
      ME_CONFIG_MONGODB_URL: mongodb://development:testpassword@mongo:27017/43
    depends_on:
      - mongo
    networks:
      - default

networks:
  default:
    name: go-ecommerce_default
    driver: bridge
